[2023-10-05 18:50:43,329] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart.get_report scheduled__2023-10-01T18:47:26.124137+00:00 [queued]>
[2023-10-05 18:50:43,344] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart.get_report scheduled__2023-10-01T18:47:26.124137+00:00 [queued]>
[2023-10-05 18:50:43,345] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-10-05 18:50:43,346] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-10-05 18:50:43,347] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-10-05 18:50:43,374] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_report> on 2023-10-01 18:47:26.124137+00:00
[2023-10-05 18:50:43,382] {standard_task_runner.py:52} INFO - Started process 1701 to run task
[2023-10-05 18:50:43,387] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'sales_mart', 'get_report', 'scheduled__2023-10-01T18:47:26.124137+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/sprint3.py', '--cfg-path', '/tmp/tmp96rwfl0v', '--error-file', '/tmp/tmpw0a5r58u']
[2023-10-05 18:50:43,388] {standard_task_runner.py:80} INFO - Job 16: Subtask get_report
[2023-10-05 18:50:43,491] {task_command.py:369} INFO - Running <TaskInstance: sales_mart.get_report scheduled__2023-10-01T18:47:26.124137+00:00 [running]> on host 2026d982a63a
[2023-10-05 18:50:43,616] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=student@example.com
AIRFLOW_CTX_DAG_OWNER=student
AIRFLOW_CTX_DAG_ID=sales_mart
AIRFLOW_CTX_TASK_ID=get_report
AIRFLOW_CTX_EXECUTION_DATE=2023-10-01T18:47:26.124137+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-10-01T18:47:26.124137+00:00
[2023-10-05 18:50:43,619] {logging_mixin.py:115} INFO - Making request get_report
[2023-10-05 18:50:44,114] {logging_mixin.py:115} INFO - Response is b'{"task_id":"MjAyMy0xMC0wNVQxODo1MDoyNglsa25fcG9wb3Y=","status":"RUNNING","data":{"report_id":null,"start_day":null,"end_date":null,"s3_path":{}}}'
[2023-10-05 18:50:54,271] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/lessons/dags/sprint3.py", line 49, in get_report
    response.raise_for_status()
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://d5dg1j9kt695d30blp03.apigw.yandexcloud.net/get_report?task_id=MjAyMy0xMC0wNVQxODo1MDoyNglsa25fcG9wb3Y=
[2023-10-05 18:50:54,312] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=sales_mart, task_id=get_report, execution_date=20231001T184726, start_date=20231005T185043, end_date=20231005T185054
[2023-10-05 18:50:54,337] {standard_task_runner.py:92} ERROR - Failed to execute job 16 for task get_report (502 Server Error: Bad Gateway for url: https://d5dg1j9kt695d30blp03.apigw.yandexcloud.net/get_report?task_id=MjAyMy0xMC0wNVQxODo1MDoyNglsa25fcG9wb3Y=; 1701)
[2023-10-05 18:50:54,365] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-10-05 18:50:54,426] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
