[2023-10-05 19:10:53,055] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart.get_increment manual__2023-10-05T19:09:37.867740+00:00 [queued]>
[2023-10-05 19:10:53,076] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart.get_increment manual__2023-10-05T19:09:37.867740+00:00 [queued]>
[2023-10-05 19:10:53,077] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-10-05 19:10:53,078] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-10-05 19:10:53,079] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-10-05 19:10:53,103] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_increment> on 2023-10-05 19:09:37.867740+00:00
[2023-10-05 19:10:53,107] {standard_task_runner.py:52} INFO - Started process 2753 to run task
[2023-10-05 19:10:53,110] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'sales_mart', 'get_increment', 'manual__2023-10-05T19:09:37.867740+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/sprint3.py', '--cfg-path', '/tmp/tmp45rr_d50', '--error-file', '/tmp/tmphdy4u7we']
[2023-10-05 19:10:53,111] {standard_task_runner.py:80} INFO - Job 40: Subtask get_increment
[2023-10-05 19:10:53,198] {task_command.py:369} INFO - Running <TaskInstance: sales_mart.get_increment manual__2023-10-05T19:09:37.867740+00:00 [running]> on host 2026d982a63a
[2023-10-05 19:10:53,291] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=student@example.com
AIRFLOW_CTX_DAG_OWNER=student
AIRFLOW_CTX_DAG_ID=sales_mart
AIRFLOW_CTX_TASK_ID=get_increment
AIRFLOW_CTX_EXECUTION_DATE=2023-10-05T19:09:37.867740+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-10-05T19:09:37.867740+00:00
[2023-10-05 19:10:53,293] {logging_mixin.py:115} INFO - Making request get_increment
[2023-10-05 19:10:53,423] {logging_mixin.py:115} INFO - Response is b'{"report_id":"TWpBeU15MHhNQzB3TlZReE9Ub3dPVG8wTUFsc2EyNWZjRzl3YjNZPQ==","date":"2023-10-05 00:00:00","status":"NOT FOUND","data":{"increment_id":null}}'
[2023-10-05 19:10:53,426] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/lessons/dags/sprint3.py", line 76, in get_increment
    raise ValueError(response)
ValueError: <Response [200]>
[2023-10-05 19:10:53,469] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=sales_mart, task_id=get_increment, execution_date=20231005T190937, start_date=20231005T191053, end_date=20231005T191053
[2023-10-05 19:10:53,490] {standard_task_runner.py:92} ERROR - Failed to execute job 40 for task get_increment (<Response [200]>; 2753)
[2023-10-05 19:10:53,526] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-10-05 19:10:53,605] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
