[2023-10-07 13:02:05,304] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart.update_f_sales scheduled__2023-09-30T12:57:59.807942+00:00 [queued]>
[2023-10-07 13:02:05,311] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart.update_f_sales scheduled__2023-09-30T12:57:59.807942+00:00 [queued]>
[2023-10-07 13:02:05,312] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-10-07 13:02:05,312] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-10-07 13:02:05,313] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-10-07 13:02:05,322] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): update_f_sales> on 2023-09-30 12:57:59.807942+00:00
[2023-10-07 13:02:05,325] {standard_task_runner.py:52} INFO - Started process 1292 to run task
[2023-10-07 13:02:05,327] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'sales_mart', 'update_f_sales', 'scheduled__2023-09-30T12:57:59.807942+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/sprint3.py', '--cfg-path', '/tmp/tmpdtlfxcpf', '--error-file', '/tmp/tmpu6eubwuw']
[2023-10-07 13:02:05,328] {standard_task_runner.py:80} INFO - Job 25: Subtask update_f_sales
[2023-10-07 13:02:05,365] {task_command.py:369} INFO - Running <TaskInstance: sales_mart.update_f_sales scheduled__2023-09-30T12:57:59.807942+00:00 [running]> on host 1af476629d92
[2023-10-07 13:02:05,407] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=student@example.com
AIRFLOW_CTX_DAG_OWNER=student
AIRFLOW_CTX_DAG_ID=sales_mart
AIRFLOW_CTX_TASK_ID=update_f_sales
AIRFLOW_CTX_EXECUTION_DATE=2023-09-30T12:57:59.807942+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-09-30T12:57:59.807942+00:00
[2023-10-07 13:02:05,414] {base.py:68} INFO - Using connection ID 'postgresql_de' for task execution.
[2023-10-07 13:02:05,419] {sql.py:315} INFO - Running statement: delete from mart.f_sales f
where f.date_id in (
    select 
        dc.date_id
    from mart.d_calendar dc 
    where dc.date_actual::date = '2023-09-30'
);

insert into mart.f_sales (date_id, item_id, customer_id, city_id, quantity, payment_amount,"status")
select 
    dc.date_id
    ,uol.item_id
    ,uol.customer_id
    ,uol.city_id
    ,uol.quantity
    ,case 
        when uol."status" = 'refunded'
        then -uol.payment_amount 
        else uol.payment_amount 
    end as payment_amount
    ,uol."status"
from staging.user_order_log uol
left join mart.d_calendar as dc on uol.date_time::Date = dc.date_actual
where uol.date_time::Date = '2023-09-30';, parameters: {'date': ('{{ ds }}',)}
[2023-10-07 13:02:05,428] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/providers/postgres/operators/postgres.py", line 94, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/usr/local/lib/python3.8/dist-packages/airflow/providers/common/sql/hooks/sql.py", line 295, in run
    self._run_command(cur, sql_statement, parameters)
  File "/usr/local/lib/python3.8/dist-packages/airflow/providers/common/sql/hooks/sql.py", line 318, in _run_command
    cur.execute(sql_statement, parameters)
psycopg2.errors.UndefinedColumn: column "status" of relation "f_sales" does not exist
LINE 9: ...id, customer_id, city_id, quantity, payment_amount,"status")
                                                              ^

[2023-10-07 13:02:05,436] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=sales_mart, task_id=update_f_sales, execution_date=20230930T125759, start_date=20231007T130205, end_date=20231007T130205
[2023-10-07 13:02:05,444] {standard_task_runner.py:92} ERROR - Failed to execute job 25 for task update_f_sales (column "status" of relation "f_sales" does not exist
LINE 9: ...id, customer_id, city_id, quantity, payment_amount,"status")
                                                              ^
; 1292)
[2023-10-07 13:02:05,460] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-10-07 13:02:05,488] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
