[2023-10-07 08:24:43,664] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart.get_increment manual__2023-10-07T08:23:34.489254+00:00 [queued]>
[2023-10-07 08:24:43,671] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart.get_increment manual__2023-10-07T08:23:34.489254+00:00 [queued]>
[2023-10-07 08:24:43,671] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-10-07 08:24:43,672] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-10-07 08:24:43,673] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-10-07 08:24:43,681] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_increment> on 2023-10-07 08:23:34.489254+00:00
[2023-10-07 08:24:43,684] {standard_task_runner.py:52} INFO - Started process 2062 to run task
[2023-10-07 08:24:43,685] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'sales_mart', 'get_increment', 'manual__2023-10-07T08:23:34.489254+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/sprint3.py', '--cfg-path', '/tmp/tmpv3kyto6i', '--error-file', '/tmp/tmpmam04e9g']
[2023-10-07 08:24:43,686] {standard_task_runner.py:80} INFO - Job 54: Subtask get_increment
[2023-10-07 08:24:43,723] {task_command.py:369} INFO - Running <TaskInstance: sales_mart.get_increment manual__2023-10-07T08:23:34.489254+00:00 [running]> on host 36d9c57a9c84
[2023-10-07 08:24:43,763] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=student@example.com
AIRFLOW_CTX_DAG_OWNER=student
AIRFLOW_CTX_DAG_ID=sales_mart
AIRFLOW_CTX_TASK_ID=get_increment
AIRFLOW_CTX_EXECUTION_DATE=2023-10-07T08:23:34.489254+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-10-07T08:23:34.489254+00:00
[2023-10-07 08:24:43,764] {logging_mixin.py:115} INFO - Making request get_increment
[2023-10-07 08:24:43,914] {logging_mixin.py:115} INFO - Response is b'{"report_id":"TWpBeU15MHhNQzB3TjFRd09Eb3lNem96Tmdsc2EyNWZjRzl3YjNZPQ==","date":"2023-10-07 00:00:00","status":"NOT FOUND","data":{"increment_id":null}}'
[2023-10-07 08:24:43,927] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/lessons/dags/sprint3.py", line 82, in get_increment
    raise ValueError(f'Increment is empty. Most probably due to error in API call.')
ValueError: Increment is empty. Most probably due to error in API call.
[2023-10-07 08:24:43,942] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=sales_mart, task_id=get_increment, execution_date=20231007T082334, start_date=20231007T082443, end_date=20231007T082443
[2023-10-07 08:24:43,948] {standard_task_runner.py:92} ERROR - Failed to execute job 54 for task get_increment (Increment is empty. Most probably due to error in API call.; 2062)
[2023-10-07 08:24:43,980] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-10-07 08:24:44,008] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
