[2023-10-07 08:21:54,654] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart.check_incr scheduled__2023-10-02T08:17:37.691037+00:00 [queued]>
[2023-10-07 08:21:54,660] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart.check_incr scheduled__2023-10-02T08:17:37.691037+00:00 [queued]>
[2023-10-07 08:21:54,661] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-10-07 08:21:54,662] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-10-07 08:21:54,662] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-10-07 08:21:54,671] {taskinstance.py:1377} INFO - Executing <Task(BranchPythonOperator): check_incr> on 2023-10-02 08:17:37.691037+00:00
[2023-10-07 08:21:54,673] {standard_task_runner.py:52} INFO - Started process 1290 to run task
[2023-10-07 08:21:54,675] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'sales_mart', 'check_incr', 'scheduled__2023-10-02T08:17:37.691037+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/sprint3.py', '--cfg-path', '/tmp/tmp6wxnie83', '--error-file', '/tmp/tmp_f_u6edp']
[2023-10-07 08:21:54,676] {standard_task_runner.py:80} INFO - Job 26: Subtask check_incr
[2023-10-07 08:21:54,710] {task_command.py:369} INFO - Running <TaskInstance: sales_mart.check_incr scheduled__2023-10-02T08:17:37.691037+00:00 [running]> on host 36d9c57a9c84
[2023-10-07 08:21:54,748] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=student@example.com
AIRFLOW_CTX_DAG_OWNER=student
AIRFLOW_CTX_DAG_ID=sales_mart
AIRFLOW_CTX_TASK_ID=check_incr
AIRFLOW_CTX_EXECUTION_DATE=2023-10-02T08:17:37.691037+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-10-02T08:17:37.691037+00:00
[2023-10-07 08:21:54,749] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 207, in execute
    branch = super().execute(context)
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/lessons/dags/sprint3.py", line 90, in if_increment
    if ti.xcom_pull(key='increment_id',task_id='get_increments') is None:
  File "/usr/local/lib/python3.8/dist-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
TypeError: xcom_pull() got an unexpected keyword argument 'task_id'
[2023-10-07 08:21:54,763] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=sales_mart, task_id=check_incr, execution_date=20231002T081737, start_date=20231007T082154, end_date=20231007T082154
[2023-10-07 08:21:54,770] {standard_task_runner.py:92} ERROR - Failed to execute job 26 for task check_incr (xcom_pull() got an unexpected keyword argument 'task_id'; 1290)
[2023-10-07 08:21:54,808] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-10-07 08:21:54,842] {local_task_job.py:273} INFO - 2 downstream tasks scheduled from follow-on schedule check
