[2023-10-05 19:13:05,819] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart.get_increment manual__2023-10-05T19:11:50.641972+00:00 [queued]>
[2023-10-05 19:13:05,833] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart.get_increment manual__2023-10-05T19:11:50.641972+00:00 [queued]>
[2023-10-05 19:13:05,834] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-10-05 19:13:05,835] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-10-05 19:13:05,835] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-10-05 19:13:05,858] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_increment> on 2023-10-05 19:11:50.641972+00:00
[2023-10-05 19:13:05,874] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'sales_mart', 'get_increment', 'manual__2023-10-05T19:11:50.641972+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/sprint3.py', '--cfg-path', '/tmp/tmpn52kc0e5', '--error-file', '/tmp/tmpc0kp97n7']
[2023-10-05 19:13:05,876] {standard_task_runner.py:80} INFO - Job 43: Subtask get_increment
[2023-10-05 19:13:05,868] {standard_task_runner.py:52} INFO - Started process 2887 to run task
[2023-10-05 19:13:05,974] {task_command.py:369} INFO - Running <TaskInstance: sales_mart.get_increment manual__2023-10-05T19:11:50.641972+00:00 [running]> on host 2026d982a63a
[2023-10-05 19:13:06,079] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=student@example.com
AIRFLOW_CTX_DAG_OWNER=student
AIRFLOW_CTX_DAG_ID=sales_mart
AIRFLOW_CTX_TASK_ID=get_increment
AIRFLOW_CTX_EXECUTION_DATE=2023-10-05T19:11:50.641972+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-10-05T19:11:50.641972+00:00
[2023-10-05 19:13:06,081] {logging_mixin.py:115} INFO - Making request get_increment
[2023-10-05 19:13:06,377] {logging_mixin.py:115} INFO - Response is b'{"report_id":"TWpBeU15MHhNQzB3TlZReE9Ub3hNVG8xTXdsc2EyNWZjRzl3YjNZPQ==","date":"2023-10-05 00:00:00","status":"NOT FOUND","data":{"increment_id":null}}'
[2023-10-05 19:13:06,382] {logging_mixin.py:115} INFO - <Response [200]>
[2023-10-05 19:13:06,383] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/lessons/dags/sprint3.py", line 77, in get_increment
    raise ValueError(f'Increment is empty. Most probably due to error in API call.')
ValueError: Increment is empty. Most probably due to error in API call.
[2023-10-05 19:13:06,413] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=sales_mart, task_id=get_increment, execution_date=20231005T191150, start_date=20231005T191305, end_date=20231005T191306
[2023-10-05 19:13:06,435] {standard_task_runner.py:92} ERROR - Failed to execute job 43 for task get_increment (Increment is empty. Most probably due to error in API call.; 2887)
[2023-10-05 19:13:06,459] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-10-05 19:13:06,531] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
