[2023-10-07 11:41:18,849] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart.check_incr manual__2023-10-07T11:40:06.345182+00:00 [queued]>
[2023-10-07 11:41:18,858] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart.check_incr manual__2023-10-07T11:40:06.345182+00:00 [queued]>
[2023-10-07 11:41:18,859] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-10-07 11:41:18,860] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-10-07 11:41:18,860] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-10-07 11:41:18,871] {taskinstance.py:1377} INFO - Executing <Task(BranchPythonOperator): check_incr> on 2023-10-07 11:40:06.345182+00:00
[2023-10-07 11:41:18,874] {standard_task_runner.py:52} INFO - Started process 1965 to run task
[2023-10-07 11:41:18,876] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'sales_mart', 'check_incr', 'manual__2023-10-07T11:40:06.345182+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/sprint3.py', '--cfg-path', '/tmp/tmpacokdox9', '--error-file', '/tmp/tmpxm2zibee']
[2023-10-07 11:41:18,877] {standard_task_runner.py:80} INFO - Job 45: Subtask check_incr
[2023-10-07 11:41:18,918] {task_command.py:369} INFO - Running <TaskInstance: sales_mart.check_incr manual__2023-10-07T11:40:06.345182+00:00 [running]> on host 70ec72ace0d7
[2023-10-07 11:41:18,955] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=student@example.com
AIRFLOW_CTX_DAG_OWNER=student
AIRFLOW_CTX_DAG_ID=sales_mart
AIRFLOW_CTX_TASK_ID=check_incr
AIRFLOW_CTX_EXECUTION_DATE=2023-10-07T11:40:06.345182+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-10-07T11:40:06.345182+00:00
[2023-10-07 11:41:18,956] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 207, in execute
    branch = super().execute(context)
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: if_increment() missing 1 required positional argument: 'task_ids'
[2023-10-07 11:41:18,962] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=sales_mart, task_id=check_incr, execution_date=20231007T114006, start_date=20231007T114118, end_date=20231007T114118
[2023-10-07 11:41:18,971] {standard_task_runner.py:92} ERROR - Failed to execute job 45 for task check_incr (if_increment() missing 1 required positional argument: 'task_ids'; 1965)
[2023-10-07 11:41:19,009] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-10-07 11:41:19,044] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
