[2023-10-07 08:08:12,299] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart.check_incr scheduled__2023-09-30T08:05:25.664213+00:00 [queued]>
[2023-10-07 08:08:12,305] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart.check_incr scheduled__2023-09-30T08:05:25.664213+00:00 [queued]>
[2023-10-07 08:08:12,306] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-10-07 08:08:12,306] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-10-07 08:08:12,307] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-10-07 08:08:12,314] {taskinstance.py:1377} INFO - Executing <Task(BranchPythonOperator): check_incr> on 2023-09-30 08:05:25.664213+00:00
[2023-10-07 08:08:12,317] {standard_task_runner.py:52} INFO - Started process 1128 to run task
[2023-10-07 08:08:12,319] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'sales_mart', 'check_incr', 'scheduled__2023-09-30T08:05:25.664213+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/sprint3.py', '--cfg-path', '/tmp/tmpyn1h5ksx', '--error-file', '/tmp/tmpgqx4bkp5']
[2023-10-07 08:08:12,320] {standard_task_runner.py:80} INFO - Job 15: Subtask check_incr
[2023-10-07 08:08:12,354] {task_command.py:369} INFO - Running <TaskInstance: sales_mart.check_incr scheduled__2023-09-30T08:05:25.664213+00:00 [running]> on host 219fbcc16ca0
[2023-10-07 08:08:12,394] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=student@example.com
AIRFLOW_CTX_DAG_OWNER=student
AIRFLOW_CTX_DAG_ID=sales_mart
AIRFLOW_CTX_TASK_ID=check_incr
AIRFLOW_CTX_EXECUTION_DATE=2023-09-30T08:05:25.664213+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-09-30T08:05:25.664213+00:00
[2023-10-07 08:08:12,395] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 207, in execute
    branch = super().execute(context)
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/lessons/dags/sprint3.py", line 89, in if_increment
    if ti.xcom_pull(key='increment_id',task_id='get_increments') == 'SUCCESS':
  File "/usr/local/lib/python3.8/dist-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
TypeError: xcom_pull() got an unexpected keyword argument 'task_id'
[2023-10-07 08:08:12,410] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=sales_mart, task_id=check_incr, execution_date=20230930T080525, start_date=20231007T080812, end_date=20231007T080812
[2023-10-07 08:08:12,416] {standard_task_runner.py:92} ERROR - Failed to execute job 15 for task check_incr (xcom_pull() got an unexpected keyword argument 'task_id'; 1128)
[2023-10-07 08:08:12,451] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-10-07 08:08:12,484] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
