[2023-10-07 12:52:32,593] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart.upload_user_order_inc manual__2023-10-07T12:51:19.432801+00:00 [queued]>
[2023-10-07 12:52:32,600] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart.upload_user_order_inc manual__2023-10-07T12:51:19.432801+00:00 [queued]>
[2023-10-07 12:52:32,601] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-10-07 12:52:32,601] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-10-07 12:52:32,602] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-10-07 12:52:32,611] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): upload_user_order_inc> on 2023-10-07 12:51:19.432801+00:00
[2023-10-07 12:52:32,614] {standard_task_runner.py:52} INFO - Started process 3471 to run task
[2023-10-07 12:52:32,616] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'sales_mart', 'upload_user_order_inc', 'manual__2023-10-07T12:51:19.432801+00:00', '--job-id', '94', '--raw', '--subdir', 'DAGS_FOLDER/sprint3.py', '--cfg-path', '/tmp/tmpdfop_dm9', '--error-file', '/tmp/tmpcar4apa0']
[2023-10-07 12:52:32,617] {standard_task_runner.py:80} INFO - Job 94: Subtask upload_user_order_inc
[2023-10-07 12:52:32,657] {task_command.py:369} INFO - Running <TaskInstance: sales_mart.upload_user_order_inc manual__2023-10-07T12:51:19.432801+00:00 [running]> on host d964b2b568e5
[2023-10-07 12:52:32,702] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=student@example.com
AIRFLOW_CTX_DAG_OWNER=student
AIRFLOW_CTX_DAG_ID=sales_mart
AIRFLOW_CTX_TASK_ID=upload_user_order_inc
AIRFLOW_CTX_EXECUTION_DATE=2023-10-07T12:51:19.432801+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-10-07T12:51:19.432801+00:00
[2023-10-07 12:52:32,710] {logging_mixin.py:115} INFO - https://storage.yandexcloud.net/s3-sprint3/cohort_18/lkn_popov/project/None/user_order_log_inc.csv
[2023-10-07 12:52:32,711] {logging_mixin.py:115} INFO - 20231007_user_order_log_inc.csv
[2023-10-07 12:52:32,814] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/lessons/dags/sprint3.py", line 96, in upload_data_to_staging
    response.raise_for_status()
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.yandexcloud.net/s3-sprint3/cohort_18/lkn_popov/project/None/user_order_log_inc.csv
[2023-10-07 12:52:32,829] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=sales_mart, task_id=upload_user_order_inc, execution_date=20231007T125119, start_date=20231007T125232, end_date=20231007T125232
[2023-10-07 12:52:32,838] {standard_task_runner.py:92} ERROR - Failed to execute job 94 for task upload_user_order_inc (404 Client Error: Not Found for url: https://storage.yandexcloud.net/s3-sprint3/cohort_18/lkn_popov/project/None/user_order_log_inc.csv; 3471)
[2023-10-07 12:52:32,869] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-10-07 12:52:32,900] {local_task_job.py:273} INFO - 3 downstream tasks scheduled from follow-on schedule check
