[2023-10-07 08:20:52,596] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart.upload_user_order_inc manual__2023-10-07T08:18:03.159973+00:00 [queued]>
[2023-10-07 08:20:52,601] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart.upload_user_order_inc manual__2023-10-07T08:18:03.159973+00:00 [queued]>
[2023-10-07 08:20:52,602] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-10-07 08:20:52,603] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-10-07 08:20:52,603] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-10-07 08:20:52,611] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): upload_user_order_inc> on 2023-10-07 08:18:03.159973+00:00
[2023-10-07 08:20:52,614] {standard_task_runner.py:52} INFO - Started process 1147 to run task
[2023-10-07 08:20:52,615] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'sales_mart', 'upload_user_order_inc', 'manual__2023-10-07T08:18:03.159973+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/sprint3.py', '--cfg-path', '/tmp/tmp69v26pjd', '--error-file', '/tmp/tmpqj__685e']
[2023-10-07 08:20:52,616] {standard_task_runner.py:80} INFO - Job 22: Subtask upload_user_order_inc
[2023-10-07 08:20:52,649] {task_command.py:369} INFO - Running <TaskInstance: sales_mart.upload_user_order_inc manual__2023-10-07T08:18:03.159973+00:00 [running]> on host 36d9c57a9c84
[2023-10-07 08:20:52,689] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=student@example.com
AIRFLOW_CTX_DAG_OWNER=student
AIRFLOW_CTX_DAG_ID=sales_mart
AIRFLOW_CTX_TASK_ID=upload_user_order_inc
AIRFLOW_CTX_EXECUTION_DATE=2023-10-07T08:18:03.159973+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-10-07T08:18:03.159973+00:00
[2023-10-07 08:20:52,696] {logging_mixin.py:115} INFO - https://storage.yandexcloud.net/s3-sprint3/cohort_18/lkn_popov/project/None/user_order_log_inc.csv
[2023-10-07 08:20:52,696] {logging_mixin.py:115} INFO - 20231007_user_order_log_inc.csv
[2023-10-07 08:20:52,745] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/lessons/dags/sprint3.py", line 104, in upload_data_to_staging
    response.raise_for_status()
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.yandexcloud.net/s3-sprint3/cohort_18/lkn_popov/project/None/user_order_log_inc.csv
[2023-10-07 08:20:52,761] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=sales_mart, task_id=upload_user_order_inc, execution_date=20231007T081803, start_date=20231007T082052, end_date=20231007T082052
[2023-10-07 08:20:52,767] {standard_task_runner.py:92} ERROR - Failed to execute job 22 for task upload_user_order_inc (404 Client Error: Not Found for url: https://storage.yandexcloud.net/s3-sprint3/cohort_18/lkn_popov/project/None/user_order_log_inc.csv; 1147)
[2023-10-07 08:20:52,789] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-10-07 08:20:52,817] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
