[2023-10-07 11:52:01,562] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart.check_incr manual__2023-10-07T11:50:49.156851+00:00 [queued]>
[2023-10-07 11:52:01,569] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart.check_incr manual__2023-10-07T11:50:49.156851+00:00 [queued]>
[2023-10-07 11:52:01,570] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-10-07 11:52:01,570] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-10-07 11:52:01,571] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-10-07 11:52:01,581] {taskinstance.py:1377} INFO - Executing <Task(BranchPythonOperator): check_incr> on 2023-10-07 11:50:49.156851+00:00
[2023-10-07 11:52:01,584] {standard_task_runner.py:52} INFO - Started process 2530 to run task
[2023-10-07 11:52:01,585] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'sales_mart', 'check_incr', 'manual__2023-10-07T11:50:49.156851+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/sprint3.py', '--cfg-path', '/tmp/tmpyjwe3x3g', '--error-file', '/tmp/tmpr21k9cc4']
[2023-10-07 11:52:01,586] {standard_task_runner.py:80} INFO - Job 57: Subtask check_incr
[2023-10-07 11:52:01,624] {task_command.py:369} INFO - Running <TaskInstance: sales_mart.check_incr manual__2023-10-07T11:50:49.156851+00:00 [running]> on host 70ec72ace0d7
[2023-10-07 11:52:01,668] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=student@example.com
AIRFLOW_CTX_DAG_OWNER=student
AIRFLOW_CTX_DAG_ID=sales_mart
AIRFLOW_CTX_TASK_ID=check_incr
AIRFLOW_CTX_EXECUTION_DATE=2023-10-07T11:50:49.156851+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-10-07T11:50:49.156851+00:00
[2023-10-07 11:52:01,677] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 207, in execute
    branch = super().execute(context)
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/lessons/dags/sprint3.py", line 91, in if_increment
    task_ids.appned('dummy')
AttributeError: 'list' object has no attribute 'appned'
[2023-10-07 11:52:01,695] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=sales_mart, task_id=check_incr, execution_date=20231007T115049, start_date=20231007T115201, end_date=20231007T115201
[2023-10-07 11:52:01,703] {standard_task_runner.py:92} ERROR - Failed to execute job 57 for task check_incr ('list' object has no attribute 'appned'; 2530)
[2023-10-07 11:52:01,718] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-10-07 11:52:01,753] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
